export const GET_INFO_THEATER_SYS_REQUEST = "GET_INFO_THEATER_SYS_REQUEST";
export const GET_INFO_THEATER_SYS_SUCCESS = "GET_INFO_THEATER_SYS_SUCCESS";
export const GET_INFO_THEATER_SYS_FAILURE = "GET_INFO_THEATER_SYS_FAILURE";
