export const GET_MOVIE_SHOWTIME_REQUEST = "GET_MOVIE_SHOWTIME_REQUEST";
export const GET_MOVIE_SHOWTIME_SUCCESS = "GET_MOVIE_SHOWTIME_SUCCESS";
export const GET_MOVIE_SHOWTIME_FAILURE = "GET_MOVIE_SHOWTIME_FAILURE";
